/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    id: "sMlER3GMR7c",
    title: "Riptide",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "The Chainsmokers",
    creatorImg:
      "https://yt3.ggpht.com/_Hx0zXq6Dqcu0XrrQB3JsmwEIJMtGYYdOxHF08JTBG34_LszhywnyVGHYiLibrzH4Vqgc8lH2g=s88-c-k-c0x00ffffff-no-nd-rj",
    subscriber: "20.0M",
    category: "Music",
    subCategory: ["trending"],
  },
  {
    id: "KI-oUttlCbM",
    title: "Ipad - Official Lyrics Video",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "The Chainsmokers",
    creatorImg:
      "https://yt3.ggpht.com/_Hx0zXq6Dqcu0XrrQB3JsmwEIJMtGYYdOxHF08JTBG34_LszhywnyVGHYiLibrzH4Vqgc8lH2g=s88-c-k-c0x00ffffff-no-nd-rj",
    subscriber: "20.0M",
    category: "Music",
    subCategory: ["newMusic"],
  },
  {
    id: "KIt3XtQPfAA",
    title: "Meet me At our Spot",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "The Chainsmokers",
    creatorImg:
      "https://yt3.ggpht.com/_Hx0zXq6Dqcu0XrrQB3JsmwEIJMtGYYdOxHF08JTBG34_LszhywnyVGHYiLibrzH4Vqgc8lH2g=s88-c-k-c0x00ffffff-no-nd-rj",
    subscriber: "20.0M",
    category: "Music",
    subCategory: ["newMusic"],
  },
  {
    id: "7mWQ38SpEf8",
    title: "All We Know",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "The Chainsmokers",
    creatorImg:
      "https://yt3.ggpht.com/_Hx0zXq6Dqcu0XrrQB3JsmwEIJMtGYYdOxHF08JTBG34_LszhywnyVGHYiLibrzH4Vqgc8lH2g=s88-c-k-c0x00ffffff-no-nd-rj",
    subscriber: "20.0M",
    category: "Music",
    subCategory: ["newMusic"],
  },
  {
    id: "RlaBTqv8tQs",
    title: "All We Know",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Kygo",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSI8g2VvHoYNQbomi9pOFpyrS7m6KehuqE7Rxsyog=s88-c-k-c0x00ffffff-no-rj-mo",
    subscriber: "10.0M",
    category: "Music",
    subCategory: ["newMusic"],
  },
  {
    id: "0b16mI9wprU",
    title:
      "Prime Time With Ravish Kumar: नैतिक बल के बिना Global Leader का बाहुबल",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "NDTV India",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTTJEVRKRq2MQmhnG83AFSZQRD6iGclKV1swgpSrg=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "10.0M",
    category: "News",
    subCategory: ["trending"],
  },
  {
    id: "gihR_OTJ8DU",
    title:
      "Prime Time With Ravish Kumar: 14 States Face Power Shortage Amid Scorching Summer",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "NDTV India",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTTJEVRKRq2MQmhnG83AFSZQRD6iGclKV1swgpSrg=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "10.0M",
    category: "News",
    subCategory: ["news"],
  },
  {
    id: "fDfI8wpRYzI",
    title:
      "Prime Time With Ravish Kumar: Fuel Prices: PM Modi Takes Aim At Opposition-Ruled States",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "NDTV India",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTTJEVRKRq2MQmhnG83AFSZQRD6iGclKV1swgpSrg=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "10.0M",
    category: "News",
    subCategory: ["trending"],
  },
  {
    id: "roMsxpdw4xE",
    title:
      "Bulldozer ka religion & news anchors ki khushi | TV Newsance Ep 168",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Newslaundry",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQdZG-k6iIKRJBIyO2FpqgcxI_ifNcUrN_p1KGTpA=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "10.0M",
    category: "News",
    subCategory: ["news"],
  },
  {
    id: "UL7fy1zb9qU",
    title: "Kashmir Files propaganda and the sham of BARC ratings",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Newslaundry",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQdZG-k6iIKRJBIyO2FpqgcxI_ifNcUrN_p1KGTpA=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "10.0M",
    category: "News",
    subCategory: ["news"],
  },
  {
    id: "DXv0bKZ1EXo",
    title:
      "G2 Esports vs. FURIA | Upper Semifinals - Day 4 | RLCS Winter Major",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Rocket League Esports",
    creatorImg:
      "https://yt3.ggpht.com/OzPYIAc2t4o0lBumylvMuAyH8qrr829W4qZcSL6fgUBl6Z8JFhOk2qzR_oLnYep9Bb6WqwQX=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "700k",
    category: "Games",
    subCategory: ["trending"],
  },
  {
    id: "RS5pIBOZwmU",
    title:
      "Team Queso vs. FURIA | Lower Quarterfinals - Day 4 | RLCS Winter Major",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Rocket League Esports",
    creatorImg:
      "https://yt3.ggpht.com/OzPYIAc2t4o0lBumylvMuAyH8qrr829W4qZcSL6fgUBl6Z8JFhOk2qzR_oLnYep9Bb6WqwQX=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "700k",
    category: "Games",
    subCategory: ["games"],
  },
  {
    id: "oEDhYdh77AM",
    title: "NRG vs. Endpoint | Group Stage - Day 2 | RLCS Winter Major",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Rocket League Esports",
    creatorImg:
      "https://yt3.ggpht.com/OzPYIAc2t4o0lBumylvMuAyH8qrr829W4qZcSL6fgUBl6Z8JFhOk2qzR_oLnYep9Bb6WqwQX=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "700k",
    category: "Games",
    subCategory: ["games"],
  },
  {
    id: "zjOCiUoMCls",
    title: "😲Is That A Spidercar?",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "PUBG MOBILE Esports",
    creatorImg:
      "https://yt3.ggpht.com/hcENTCvCYbEDmg0P4en0juloN_WrZhlMDyBjiHC3AdEVqvRWCTIIDYbYA1WTwgjB5PNfP6E6=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "700k",
    category: "Games",
    subCategory: ["games"],
  },
  {
    id: "kF_scF9FXiA",
    title: "🔥Highlights - PMPL South Asia Finals Day 1",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "PUBG MOBILE Esports",
    creatorImg:
      "https://yt3.ggpht.com/hcENTCvCYbEDmg0P4en0juloN_WrZhlMDyBjiHC3AdEVqvRWCTIIDYbYA1WTwgjB5PNfP6E6=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "700k",
    category: "Games",
    subCategory: ["trending"],
  },
  {
    id: "Npu7jkJk5nM",
    title: "Our data is GONE... Again - Petabyte Project Recovery Part 1",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Linus Tech Tips",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSZnNA3eg_fDwUgsCxpqMnVWu3UGo-Rln4621ncIQ=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "13.4M",
    category: "Tech",
    subCategory: ["Tech"],
  },
  {
    id: "aHnd6PAd4C0",
    title: "We Bought 6 Dead GPUs. Can We Fix Them?",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Linus Tech Tips",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSZnNA3eg_fDwUgsCxpqMnVWu3UGo-Rln4621ncIQ=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "13.4M",
    category: "Tech",
    subCategory: ["trending", "latest"],
  },
  {
    id: "ELsYC-N7hgc",
    title: "I Can’t Believe I Liked This…",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Linus Tech Tips",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSZnNA3eg_fDwUgsCxpqMnVWu3UGo-Rln4621ncIQ=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "13.4M",
    category: "Tech",
    subCategory: ["Tech"],
  },
  {
    id: "pFYGZmdXF6s",
    title: "Apple removed the notch!?",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Techlinked",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTxqKm4RdnoWi_RtzgNNASy4nbciHGOj8QReqc_OQ=s88-c-k-c0x00ffffff-no-rj",
    subscriber: "13.4M",
    category: "Tech",
    subCategory: ["Tech"],
  },
  {
    id: "YpZqzM_fDqI&t",
    title: "The Prices... They're Back...",
    createdAt: "9 Dec 2017",
    views: "14,139,602",
    likes: "269kk",
    creator: "Techlinked",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSZnNA3eg_fDwUgsCxpqMnVWu3UGo-Rln4621ncIQ=s176-c-k-c0x00ffffff-no-rj",
    subscriber: "13.4M",
    category: "Tech",
    subCategory: ["Tech"],
  },
];
